// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WlBannerColumns holds the columns for the "wl_banner" table.
	WlBannerColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "endpoint", Type: field.TypeString, Comment: "Endpoint | 使用端", Default: ""},
		{Name: "module", Type: field.TypeString, Comment: "Module | 模块", Default: ""},
		{Name: "file_type", Type: field.TypeUint8, Comment: "File's type | 文件类型", Default: 2},
		{Name: "path", Type: field.TypeString, Comment: "File path | 文件路径", Default: ""},
		{Name: "jump_url", Type: field.TypeString, Nullable: true, Comment: "Jump url | 跳转地址", Default: ""},
		{Name: "file_id", Type: field.TypeUUID, Unique: true},
	}
	// WlBannerTable holds the schema information for the "wl_banner" table.
	WlBannerTable = &schema.Table{
		Name:       "wl_banner",
		Comment:    "轮播图配置表",
		Columns:    WlBannerColumns,
		PrimaryKey: []*schema.Column{WlBannerColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wl_banner_fms_files_banner",
				Columns:    []*schema.Column{WlBannerColumns[9]},
				RefColumns: []*schema.Column{FmsFilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// WlExchangeColumns holds the columns for the "wl_exchange" table.
	WlExchangeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "player_id", Type: field.TypeUint64, Comment: "player 's id | 兑换者ID", Default: 0},
		{Name: "transaction_id", Type: field.TypeString, Comment: "transaction id | 交易ID", Default: ""},
		{Name: "type", Type: field.TypeUint32, Comment: "type | 兑换类型：1=币兑羊；2=羊兑币", Default: 0},
		{Name: "coin_num", Type: field.TypeUint32, Comment: "coin amount| 币数量", Default: 0},
		{Name: "lamp_num", Type: field.TypeUint32, Comment: "lamp amount | 羊数量", Default: 0},
	}
	// WlExchangeTable holds the schema information for the "wl_exchange" table.
	WlExchangeTable = &schema.Table{
		Name:       "wl_exchange",
		Comment:    "兑换表",
		Columns:    WlExchangeColumns,
		PrimaryKey: []*schema.Column{WlExchangeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_player_id",
				Unique:  false,
				Columns: []*schema.Column{WlExchangeColumns[4]},
			},
		},
	}
	// FmsFilesColumns holds the columns for the "fms_files" table.
	FmsFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "File's name | 文件名称"},
		{Name: "file_type", Type: field.TypeUint8, Comment: "File's type | 文件类型"},
		{Name: "size", Type: field.TypeUint64, Comment: "File's size | 文件大小"},
		{Name: "path", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString, Comment: "User's UUID | 用户的 UUID"},
		{Name: "md5", Type: field.TypeString, Comment: "The md5 of the file | 文件的 md5"},
	}
	// FmsFilesTable holds the schema information for the "fms_files" table.
	FmsFilesTable = &schema.Table{
		Name:       "fms_files",
		Columns:    FmsFilesColumns,
		PrimaryKey: []*schema.Column{FmsFilesColumns[0]},
	}
	// WlOrderColumns holds the columns for the "wl_order" table.
	WlOrderColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "player_id", Type: field.TypeUint64, Comment: "player id | 玩家ID", Default: 0},
		{Name: "type", Type: field.TypeString, Comment: "order type | 订单类型: deposit=充值订单；withdraw=提现订单", Default: ""},
		{Name: "code", Type: field.TypeString, Comment: "order code | 订单号", Default: ""},
		{Name: "transaction_id", Type: field.TypeString, Comment: "transaction is | 交易号", Default: ""},
		{Name: "from_address", Type: field.TypeString, Comment: "transfer from address | 汇出钱包地址", Default: ""},
		{Name: "to_address", Type: field.TypeString, Comment: "transfer to address | 汇入钱包地址", Default: ""},
		{Name: "num", Type: field.TypeFloat64, Comment: "coin amount | 数量", Default: 0},
		{Name: "handling_fee", Type: field.TypeFloat64, Comment: "handling_fee | 对提币操作生效，提币手续费", Default: 0},
		{Name: "network", Type: field.TypeString, Comment: "网络", Default: ""},
		{Name: "remark", Type: field.TypeString, Comment: "remark | 备注", Default: ""},
	}
	// WlOrderTable holds the schema information for the "wl_order" table.
	WlOrderTable = &schema.Table{
		Name:       "wl_order",
		Comment:    "订单表",
		Columns:    WlOrderColumns,
		PrimaryKey: []*schema.Column{WlOrderColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_player_id",
				Unique:  false,
				Columns: []*schema.Column{WlOrderColumns[4]},
			},
			{
				Name:    "uniq_code",
				Unique:  true,
				Columns: []*schema.Column{WlOrderColumns[6]},
			},
		},
	}
	// WlOriginInviteCodeColumns holds the columns for the "wl_origin_invite_code" table.
	WlOriginInviteCodeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "code", Type: field.TypeString, Comment: "邀请码", Default: ""},
	}
	// WlOriginInviteCodeTable holds the schema information for the "wl_origin_invite_code" table.
	WlOriginInviteCodeTable = &schema.Table{
		Name:       "wl_origin_invite_code",
		Comment:    "原始邀请码管理表",
		Columns:    WlOriginInviteCodeColumns,
		PrimaryKey: []*schema.Column{WlOriginInviteCodeColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "uniq_invite_code",
				Unique:  true,
				Columns: []*schema.Column{WlOriginInviteCodeColumns[4]},
			},
		},
	}
	// WlPlayerColumns holds the columns for the "wl_player" table.
	WlPlayerColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "player name | 用户名称", Default: ""},
		{Name: "email", Type: field.TypeString, Comment: "email | 邮箱", Default: ""},
		{Name: "password", Type: field.TypeString, Comment: "password | 密码", Default: ""},
		{Name: "transaction_password", Type: field.TypeString, Comment: "transaction password | 交易密码", Default: ""},
		{Name: "lamp", Type: field.TypeFloat32, Comment: "lamp | 小羊余额", Default: 0},
		{Name: "rank", Type: field.TypeUint32, Comment: "rank | 代理等级", Default: 0},
		{Name: "amount", Type: field.TypeFloat64, Comment: "amount | 账户余额", Default: 0},
		{Name: "deposit_address", Type: field.TypeString, Comment: "deposit address | 充值地址", Default: ""},
		{Name: "invited_num", Type: field.TypeUint32, Comment: "invite people | 代理发展人数", Default: 0},
		{Name: "total_income", Type: field.TypeFloat64, Comment: "total income | 代理总收益", Default: 0},
		{Name: "profit_and_loss", Type: field.TypeFloat32, Comment: "profit and loss | 总盈亏数", Default: 0},
		{Name: "recent_100_win_percent", Type: field.TypeFloat32, Comment: "recent 100 win percent | 近100场胜率", Default: 0},
		{Name: "invite_code", Type: field.TypeString, Comment: "invite code | 邀请码", Default: ""},
		{Name: "invited_code", Type: field.TypeString, Comment: "the inviter 's invite code | 邀请人邀请码", Default: ""},
		{Name: "system_commission", Type: field.TypeFloat32, Comment: "system commission percent | 平台收益分成比例", Default: 0},
		{Name: "inviter_id", Type: field.TypeUint64, Nullable: true, Comment: "the inviter id | 邀请人ID", Default: 0},
	}
	// WlPlayerTable holds the schema information for the "wl_player" table.
	WlPlayerTable = &schema.Table{
		Name:       "wl_player",
		Comment:    "玩家表",
		Columns:    WlPlayerColumns,
		PrimaryKey: []*schema.Column{WlPlayerColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wl_player_wl_player_invitees",
				Columns:    []*schema.Column{WlPlayerColumns[19]},
				RefColumns: []*schema.Column{WlPlayerColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "uniq_email",
				Unique:  true,
				Columns: []*schema.Column{WlPlayerColumns[5]},
			},
			{
				Name:    "uniq_invite_code",
				Unique:  true,
				Columns: []*schema.Column{WlPlayerColumns[16]},
			},
			{
				Name:    "idx_inviter_id",
				Unique:  false,
				Columns: []*schema.Column{WlPlayerColumns[19]},
			},
			{
				Name:    "idx_invited_code",
				Unique:  false,
				Columns: []*schema.Column{WlPlayerColumns[17]},
			},
		},
	}
	// WlRewardColumns holds the columns for the "wl_reward" table.
	WlRewardColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "to_id", Type: field.TypeUint64, Comment: "reward to player 's id | 奖励对象ID", Default: 0},
		{Name: "contributor_id", Type: field.TypeUint64, Comment: "contributor 's id | 贡献者ID,平台为0", Default: 0},
		{Name: "contributor_email", Type: field.TypeString, Comment: "contributor 's email | 贡献者邮箱，平台为system", Default: ""},
		{Name: "contributor_level", Type: field.TypeUint32, Comment: "contributor level | 贡献者属于奖励对象第几级", Default: 1},
		{Name: "num", Type: field.TypeFloat32, Comment: "lamb amount | 数量", Default: 0},
		{Name: "formula", Type: field.TypeString, Comment: "计算公式", Default: ""},
		{Name: "remark", Type: field.TypeString, Comment: "remark | 备注", Default: ""},
	}
	// WlRewardTable holds the schema information for the "wl_reward" table.
	WlRewardTable = &schema.Table{
		Name:       "wl_reward",
		Comment:    "奖励表",
		Columns:    WlRewardColumns,
		PrimaryKey: []*schema.Column{WlRewardColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_to",
				Unique:  false,
				Columns: []*schema.Column{WlRewardColumns[4]},
			},
		},
	}
	// WlRoundColumns holds the columns for the "wl_round" table.
	WlRoundColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "round_count", Type: field.TypeUint32, Comment: "Round Count | 当日累计回合数"},
		{Name: "total_round_count", Type: field.TypeUint64, Nullable: true, Comment: "累计第几回合", Default: 0},
		{Name: "start_at", Type: field.TypeTime, Comment: "Start Time | 回合开始时间（包括倒计时）"},
		{Name: "open_at", Type: field.TypeTime, Comment: "Open Time | 回合开奖时间"},
		{Name: "end_at", Type: field.TypeTime, Comment: "End Time | 回合结束时间"},
		{Name: "selected_fold", Type: field.TypeUint32, Comment: "选中的羊圈号码", Default: 0},
	}
	// WlRoundTable holds the schema information for the "wl_round" table.
	WlRoundTable = &schema.Table{
		Name:       "wl_round",
		Comment:    "回合表",
		Columns:    WlRoundColumns,
		PrimaryKey: []*schema.Column{WlRoundColumns[0]},
	}
	// WlRoundInvestColumns holds the columns for the "wl_round_invest" table.
	WlRoundInvestColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "player_id", Type: field.TypeUint64, Comment: "玩家ID", Default: 0},
		{Name: "player_email", Type: field.TypeString, Comment: "玩家邮箱", Default: ""},
		{Name: "fold_no", Type: field.TypeUint32, Comment: "羊圈号码", Default: 0},
		{Name: "lamb_num", Type: field.TypeUint32, Comment: "投注羊数量", Default: 0},
		{Name: "profit_and_loss", Type: field.TypeFloat32, Comment: "投注盈亏结果", Default: 0},
		{Name: "round_count", Type: field.TypeUint32, Nullable: true, Comment: "当日第几回合", Default: 0},
		{Name: "total_round_count", Type: field.TypeUint64, Nullable: true, Comment: "累计第几回合", Default: 0},
		{Name: "round_id", Type: field.TypeUint64, Nullable: true, Comment: "所属回合ID", Default: 0},
	}
	// WlRoundInvestTable holds the schema information for the "wl_round_invest" table.
	WlRoundInvestTable = &schema.Table{
		Name:       "wl_round_invest",
		Comment:    "回合投注情况表",
		Columns:    WlRoundInvestColumns,
		PrimaryKey: []*schema.Column{WlRoundInvestColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wl_round_invest_wl_round_invest",
				Columns:    []*schema.Column{WlRoundInvestColumns[10]},
				RefColumns: []*schema.Column{WlRoundColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "idx_round",
				Unique:  false,
				Columns: []*schema.Column{WlRoundInvestColumns[10]},
			},
			{
				Name:    "idx_player",
				Unique:  false,
				Columns: []*schema.Column{WlRoundInvestColumns[3]},
			},
			{
				Name:    "idx_total_count",
				Unique:  false,
				Columns: []*schema.Column{WlRoundInvestColumns[9]},
			},
		},
	}
	// WlRoundLambFoldColumns holds the columns for the "wl_round_lamb_fold" table.
	WlRoundLambFoldColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "fold_no", Type: field.TypeUint32, Comment: "羊圈号", Default: 0},
		{Name: "lamb_num", Type: field.TypeUint32, Comment: "投注羊数量", Default: 0},
		{Name: "profit_and_loss", Type: field.TypeFloat32, Comment: "投注盈亏结果", Default: 0},
		{Name: "round_count", Type: field.TypeUint32, Nullable: true, Comment: "当日第几回合", Default: 0},
		{Name: "total_round_count", Type: field.TypeUint64, Nullable: true, Comment: "累计第几回合", Default: 0},
		{Name: "round_id", Type: field.TypeUint64, Nullable: true, Comment: "所属回合ID", Default: 0},
	}
	// WlRoundLambFoldTable holds the schema information for the "wl_round_lamb_fold" table.
	WlRoundLambFoldTable = &schema.Table{
		Name:       "wl_round_lamb_fold",
		Comment:    "回合羊圈情况表",
		Columns:    WlRoundLambFoldColumns,
		PrimaryKey: []*schema.Column{WlRoundLambFoldColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "wl_round_lamb_fold_wl_round_fold",
				Columns:    []*schema.Column{WlRoundLambFoldColumns[8]},
				RefColumns: []*schema.Column{WlRoundColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "idx_round",
				Unique:  false,
				Columns: []*schema.Column{WlRoundLambFoldColumns[8]},
			},
			{
				Name:    "idx_total_count",
				Unique:  false,
				Columns: []*schema.Column{WlRoundLambFoldColumns[7]},
			},
		},
	}
	// WlSettingColumns holds the columns for the "wl_setting" table.
	WlSettingColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建日期"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time | 修改日期"},
		{Name: "status", Type: field.TypeUint8, Nullable: true, Comment: "Status 1: normal 2: ban | 状态 1 正常 2 禁用", Default: 1},
		{Name: "name", Type: field.TypeString, Comment: "show name | 配置名称", Default: ""},
		{Name: "module", Type: field.TypeString, Comment: "module | 模块", Default: ""},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Comment: "value of setting | 配置值", Default: ""},
	}
	// WlSettingTable holds the schema information for the "wl_setting" table.
	WlSettingTable = &schema.Table{
		Name:       "wl_setting",
		Comment:    "系统配置表",
		Columns:    WlSettingColumns,
		PrimaryKey: []*schema.Column{WlSettingColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WlBannerTable,
		WlExchangeTable,
		FmsFilesTable,
		WlOrderTable,
		WlOriginInviteCodeTable,
		WlPlayerTable,
		WlRewardTable,
		WlRoundTable,
		WlRoundInvestTable,
		WlRoundLambFoldTable,
		WlSettingTable,
	}
)

func init() {
	WlBannerTable.ForeignKeys[0].RefTable = FmsFilesTable
	WlBannerTable.Annotation = &entsql.Annotation{
		Table:     "wl_banner",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlExchangeTable.Annotation = &entsql.Annotation{
		Table:     "wl_exchange",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	FmsFilesTable.Annotation = &entsql.Annotation{
		Table: "fms_files",
	}
	WlOrderTable.Annotation = &entsql.Annotation{
		Table:     "wl_order",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlOriginInviteCodeTable.Annotation = &entsql.Annotation{
		Table:     "wl_origin_invite_code",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlPlayerTable.ForeignKeys[0].RefTable = WlPlayerTable
	WlPlayerTable.Annotation = &entsql.Annotation{
		Table:     "wl_player",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlRewardTable.Annotation = &entsql.Annotation{
		Table:     "wl_reward",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlRoundTable.Annotation = &entsql.Annotation{
		Table:     "wl_round",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlRoundInvestTable.ForeignKeys[0].RefTable = WlRoundTable
	WlRoundInvestTable.Annotation = &entsql.Annotation{
		Table:     "wl_round_invest",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlRoundLambFoldTable.ForeignKeys[0].RefTable = WlRoundTable
	WlRoundLambFoldTable.Annotation = &entsql.Annotation{
		Table:     "wl_round_lamb_fold",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
	WlSettingTable.Annotation = &entsql.Annotation{
		Table:     "wl_setting",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_general_ci",
	}
}
