// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Banner is the predicate function for banner builders.
type Banner func(*sql.Selector)

// Exchange is the predicate function for exchange builders.
type Exchange func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OriginInviteCode is the predicate function for origininvitecode builders.
type OriginInviteCode func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Reward is the predicate function for reward builders.
type Reward func(*sql.Selector)

// Round is the predicate function for round builders.
type Round func(*sql.Selector)

// RoundInvest is the predicate function for roundinvest builders.
type RoundInvest func(*sql.Selector)

// RoundLambFold is the predicate function for roundlambfold builders.
type RoundLambFold func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)
